### ISSUE TITLE
Feature request: Allow generic TypeMapper without type argument

### ISSUE THREAD

**Issue by jonsa** [RSuter/NJsonSchema#425]
I would like a TypeMapper of type `Gen<>` to match an actual type of `Gen<Foo>` or any other class that replaces `Foo`.

See reasoning below.

I was about to create a pull request with
```c#
var typeMapper = Settings.TypeMappers.FirstOrDefault(m => m.MappedType == type);

if (typeMapper == null && type.GetTypeInfo().IsGenericType)
{
    var genericType = type.GetGenericTypeDefinition();
    typeMapper = Settings.TypeMappers.FirstOrDefault(m => m.MappedType == genericType);
}

if (typeMapper != null)
{
    // ...
}
```
in [JsonSchemaGenerator.cs#L227-L232](https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema/Generation/JsonSchemaGenerator.cs#L227-L232)

But as I was creating a unit test to cover this I sensed this might require a deeper change. Because the output I get is ```$ref: "#/definitions/Gen`1"``` instead of `$ref: "#/definitions/GenOfFoo"`.

So why would I find this useful?

I'm using NSwag to describe my web api and when my model does not validate I return with `BadRequest(ModelState)`. This results in a response of type `SerializableError` which is just a dictionary with keys matching my model and values being a list of error strings. If I set `SerializableError` as my `SwaggerResponse` type I get a response type of `{}`. Not so informative in other words.

My idea here is that I create a generic placeholder class `ErrorResponse<T>` as `SwaggerResponse`, with my model as generic argument. Use a type mapper of type `ErrorResponse<>` and have that parse the inner type, extract the properties and generate a proper response model.

**Comment by RSuter** [comment]
I think this is a scenario we should support.. can you create this pr with your type mapper impl and a unit test? I will look into it then...

**Comment by RSuter** [comment]
I added some unit tests and the support for generic type mappers. If this does not work for your scenario, please reopen the issue and publish some samples...

**Comment by jonsa** [comment]
I've finally managed to play around with this and I don't think this covers my use case.

I have an example project here [WebApiDemo](https://github.com/jonsa/WebApiDemo)

But the gist of it is.
```C#
public class ValueModel
{
    [Required]
    public string Value { get; set; }
}

public class ErrorResponse<T>
{
}

public class ErrorResponseTypeMapper : ITypeMapper
{
    public Type MappedType => typeof(ErrorResponse<>);

    public bool UseReference => true;

    public async Task GenerateSchemaAsync(JsonSchema4 schema, TypeMapperContext context)
    {
        // Parse type argument, extract property names and give them a string[] type.
    }
}

public class ValuesController : Controller
{
    [SwaggerResponse(HttpStatusCode.BadRequest, typeof(ErrorResponse<ValueModel>))]
    public void Post([FromBody]ValueModel value)
    {
    }
}

public class Startup
{
    public void Configure(IApplicationBuilder app, IHostingEnvironment env)
    {
        var settings = new SwaggerUiSettings();

        settings.TypeMappers.Add(new ErrorResponseTypeMapper());

        app.UseSwaggerUi(typeof(Startup).GetTypeInfo().Assembly, settings);
    }
}
```

If I run the project mentioned above and visiting the `swagger.json` url I'm getting the following exception trace
```
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at NSwag.SwaggerGeneration.SwaggerGenerator.<GenerateAndAppendSchemaFromTypeAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.SwaggerGeneration.WebApi.Processors.OperationResponseProcessor.<ProcessAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.SwaggerGeneration.WebApi.WebApiToSwaggerGenerator.<RunOperationProcessorsAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.SwaggerGeneration.WebApi.WebApiToSwaggerGenerator.<AddOperationDescriptionsToDocumentAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.SwaggerGeneration.WebApi.WebApiToSwaggerGenerator.<GenerateForControllerAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.SwaggerGeneration.WebApi.WebApiToSwaggerGenerator.<GenerateForControllersAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.AspNetCore.SwaggerMiddleware.<GenerateSwaggerAsync>d__8.MoveNext()
```

I've tracked down the cause which is [JsonSchemaResolver::GetSchema](https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema/JsonSchemaResolver.cs#L50) being called called with a `Type` argument of ```WebApiDemo.NSwag.ErrorResponse`1[WebApiDemo.Models.ValueModel]``` from [SwaggerGenerator.cs#L202](https://github.com/RSuter/NSwag/blob/master/src/NSwag.SwaggerGeneration/SwaggerGenerator.cs#L202) which is not registered in the `JsonSchemaResolver::_mappings` property.
