### ISSUE TITLE
Schema having properties with names starting with symbol "$" cannot be parsed

### ISSUE THREAD

**Issue by gandrisl** [RSuter/NJsonSchema#472]
JsonSchema4.FromJsonAsync throws NullReferenceException with following schema. 

`{
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "$type": {
        "type": "string",
        "enum": [ "file" ]
        },
        "Id": {
        "type": "string",
        "format": "guid"
        },
        "Name": {
        "type": "string"
        }
    },
    "required": [ "$type", "Id", "Name" ]
}`

System.NullReferenceException: Object reference not set to an instance of an object.
    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue, Object& newValue, String& id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.PopulateInternal(JsonReader reader, Object target)
   at NJsonSchema.ExtensionDataDeserializationConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NJsonSchema.JsonSchema4.<FromJsonAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NJsonSchema.JsonSchema4.<FromJsonAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NJsonSchema.JsonSchema4.<FromJsonAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

**Comment by RSuter** [comment]
This is an exception with Newtonsoft.Json, I couldnt find a solutoin. Setting TypeNameHandling.None in FromJsonAsync also does not work... Somehow Newtonsoft.Json expects a string in $type and then fails because it is an object...

**Comment by gandrisl** [comment]
Have you tried setting `MetadataPropertyHandling` to `MetadataPropertyHandling.Ignore`?

**Comment by RSuter** [comment]
Thanks, this is what i set now, see commit (new version of NJS already released)

**Comment by duyang76** [comment]
Hi RSuter, the c# class generated from the schema (using CSharpGenerator class) has variables and properties starting with $ sign. How can I avoid that behavior? Is there a setting for that?

        private string _$type;
        [Newtonsoft.Json.JsonProperty("$type", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string $type
        {
            get { return _$type; }
