### ISSUE TITLE
List of enums 

### ISSUE THREAD

**Issue by Ishayu** [RSuter/NJsonSchema#475]
Hi RSuter,

We recently ran into an issue where someone had written a JSON schema which contained an array of enums.

Here is an example of what can appear: (imagine this is required)

```
"ListEnum": {
    "type": "array",
    "items": {    
        "type": "string",
        "enum": [
            "Element One",
            "Element Two",
            "Element Three"
        ]
    }
},
```

This gives rise to the following C# code:

There will be an object which contains
`private ObservableCollection<ListEnum> _listEnum = new ObservableCollection<ListEnum>();`

as well as

```
[JsonProperty("ListEnum", Required = Required.Always)]
[Required]
public ObservableCollection<ListEnum> ListEnum
{
    get { return _listEnum; }
    set
    {
        if (_listEnum!= value)
        {
            _listEnum= value;
            RaisePropertyChanged();
        }
    }
}
```

And that all looks great, except if you then try to use Newtonsoft's JSON.NET with this, it requires the following addition to the JSON Properties:
`ItemConverterType=typeof(StringEnumConverter)`

So the expected result should be:
```
[JsonProperty("ListEnum", Required = Required.Always, ItemConverterType=typeof(StringEnumConverter))]
[Required]
public ObservableCollection<ListEnum> ListEnum
{
    get { return _listEnum; }
    set
    {
        if (_listEnum!= value)
        {
            _listEnum= value;
            RaisePropertyChanged();
        }
    }
}
```

Otherwise, an exception will be raised by JSON.NET and it will refuse to deserialize correctly.

We've so far managed to fix it by inserting the element manually when needed, but I hope you'll be willing to look into this.

**Comment by RSuter** [comment]
Strange, this should already be handled: 

https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema.CodeGeneration.CSharp/Templates/ClassTemplate.tt#L24

and:

https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema.CodeGeneration/Models/PropertyModelBase.cs#L54

Are you using the latest version of NJS?

**Comment by Ishayu** [comment]
Hi RSuter,

I definitely thought I was, but it turns out NPM had done some shenaniganry where an old version was being falsely reported as a new one and linked up nicely. Once I went into packages.config and cleaned it up, the newest version was downloaded correctly.

I apologize for the false report.

You may close this.

I've still got some bugs here though. They are somewhat related to this, but I perfectly understand if you want me to make new bug reports instead - and I will do so if you request. Nevertheless, I will descirbe them here.

Concrete example from our actual code:
```
              "sekundaerForretningshaendelse": {
                "type": "array",
                "description": "EAID_A2B9B2EF_86F2_4f1d_87C0_1804A7071486.EAID_A0A706C1_027A_46ec_AC79_9138DA725DF5",
                "items": {
                  "title": "sekundaerForretningshaendelse",
                  "description": "EAID_A0A706C1_027A_46ec_AC79_9138DA725DF5",
                  "type": "string",
                  "enum": [
                    "Afledt ændring",
                    "Anden ændring",
                    "Arealændring på Ejerlejlighed",
                    "Ejerlejlighed bortfaldet",
                    "Ejerlejlighed tilkommet",
                    "Arealændring på Jordstykke",
                    "BPFG med oprindelse 'Matriklen - stedfæstet' bortfaldet",
                    "BPFG med oprindelse 'Matriklen - ikke stedfæstet' bortfaldet",
                    "BPFG med oprindelse 'Matriklen - ikke stedfæstet' tilkommet",
                    "Oprindelse for BPFG ændret til 'Matriklen - stedfæstet'",
                    "Registrering af relation fra SFE til BPFG bortfaldet",
                    "Registrering af relation fra SFE til BPFG tilkommet",
                    "Registrering af SFE som Hovedejendom for ejerlejlighedsfællesskab bortfaldet",
                    "Registrering af SFE som Hovedejendom for ejerlejlighedsfællesskab tilkommet",
                    "Noteringsændring på Jordstykke",
                    "Jordstykke(r) bortfaldet",
                    "Noteringsændring på ejendom",
                    "Jordstykke(r) tilkommet"
                  ]
                }
              }
```

Becomes:
```
        /// <summary>EAID_A2B9B2EF_86F2_4f1d_87C0_1804A7071486.EAID_A0A706C1_027A_46ec_AC79_9138DA725DF5</summary>
        [Newtonsoft.Json.JsonProperty("sekundaerForretningshaendelse", Required = Newtonsoft.Json.Required.Always, ItemConverterType = typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.ObjectModel.ObservableCollection<Anonymous2> SekundaerForretningshaendelse
        {
            get { return _sekundaerForretningshaendelse; }
            set 
            {
                if (_sekundaerForretningshaendelse != value)
                {
                    _sekundaerForretningshaendelse = value; 
                    RaisePropertyChanged();
                }
            }
        }
```

where Anonymous2 is
```
    /// <summary>EAID_A0A706C1_027A_46ec_AC79_9138DA725DF5</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.6.0.0")]
    public enum Anonymous2
    {
        [System.Runtime.Serialization.EnumMember(Value = "Afledt ændring")]
        Afledt_ændring = 0,
    
        [System.Runtime.Serialization.EnumMember(Value = "Anden ændring")]
        Anden_ændring = 1,
    
        [System.Runtime.Serialization.EnumMember(Value = "Arealændring på Ejerlejlighed")]
        Arealændring_på_Ejerlejlighed = 2,
    
        [System.Runtime.Serialization.EnumMember(Value = "Ejerlejlighed bortfaldet")]
        Ejerlejlighed_bortfaldet = 3,
    
        [System.Runtime.Serialization.EnumMember(Value = "Ejerlejlighed tilkommet")]
        Ejerlejlighed_tilkommet = 4,
    
        [System.Runtime.Serialization.EnumMember(Value = "Arealændring på Jordstykke")]
        Arealændring_på_Jordstykke = 5,
    
        [System.Runtime.Serialization.EnumMember(Value = "BPFG med oprindelse 'Matriklen - stedfæstet' bortfaldet")]
        BPFG_med_oprindelse_'Matriklen__stedfæstet'_bortfaldet = 6,
    
        [System.Runtime.Serialization.EnumMember(Value = "BPFG med oprindelse 'Matriklen - ikke stedfæstet' bortfaldet")]
        BPFG_med_oprindelse_'Matriklen__ikke_stedfæstet'_bortfaldet = 7,
    
        [System.Runtime.Serialization.EnumMember(Value = "BPFG med oprindelse 'Matriklen - ikke stedfæstet' tilkommet")]
        BPFG_med_oprindelse_'Matriklen__ikke_stedfæstet'_tilkommet = 8,
    
        [System.Runtime.Serialization.EnumMember(Value = "Oprindelse for BPFG ændret til 'Matriklen - stedfæstet'")]
        Oprindelse_for_BPFG_ændret_til_'Matriklen__stedfæstet' = 9,
    
        [System.Runtime.Serialization.EnumMember(Value = "Registrering af relation fra SFE til BPFG bortfaldet")]
        Registrering_af_relation_fra_SFE_til_BPFG_bortfaldet = 10,
    
        [System.Runtime.Serialization.EnumMember(Value = "Registrering af relation fra SFE til BPFG tilkommet")]
        Registrering_af_relation_fra_SFE_til_BPFG_tilkommet = 11,
    
        [System.Runtime.Serialization.EnumMember(Value = "Registrering af SFE som Hovedejendom for ejerlejlighedsfællesskab bortfaldet")]
        Registrering_af_SFE_som_Hovedejendom_for_ejerlejlighedsfællesskab_bortfaldet = 12,
    
        [System.Runtime.Serialization.EnumMember(Value = "Registrering af SFE som Hovedejendom for ejerlejlighedsfællesskab tilkommet")]
        Registrering_af_SFE_som_Hovedejendom_for_ejerlejlighedsfællesskab_tilkommet = 13,
    
        [System.Runtime.Serialization.EnumMember(Value = "Noteringsændring på Jordstykke")]
        Noteringsændring_på_Jordstykke = 14,
    
        [System.Runtime.Serialization.EnumMember(Value = "Jordstykke(r) bortfaldet")]
        Jordstykke(r)_bortfaldet = 15,
    
        [System.Runtime.Serialization.EnumMember(Value = "Noteringsændring på ejendom")]
        Noteringsændring_på_ejendom = 16,
    
        [System.Runtime.Serialization.EnumMember(Value = "Jordstykke(r) tilkommet")]
        Jordstykke(r)_tilkommet = 17,
    
    }
```

Two problems here: 
1) The name of the property is clearly given in he title field, yet the code generator makes no attempt to guess a type name based on that.
2) The generated enums are not sanitized correctly, leading to quotes and paranthesis in them, which is invalid C# code.

Furthermore, https://github.com/RSuter/NJsonSchema/issues/397 has returned in this version.

Specifically, when generating code for 
```
              "paataenktHandling": {
                "title": "paataenktHandling",
                "description": "EAID_D38C4D27_B57C_4356_89E1_05E8DA0250B6",
                "type": [
                  "string",
                  "null"
                ],
                "enum": [
                  "Ændring",
                  "Nyoprettelse",
                  "Udgår",
                  null
                ]
              }
```

You will run into this exception:
```
System.NullReferenceException was unhandled
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=NJsonSchema.CodeGeneration.CSharp
  StackTrace:
       at NJsonSchema.CodeGeneration.CSharp.Models.EnumTemplateModel.get_Enums()
       at NJsonSchema.CodeGeneration.CSharp.Templates.EnumTemplate.TransformText()
       at NJsonSchema.CodeGeneration.CSharp.Templates.EnumTemplate.Render()
       at NJsonSchema.CodeGeneration.CSharp.CSharpGenerator.GenerateEnum(String typeName)
       at NJsonSchema.CodeGeneration.CSharp.CSharpGenerator.GenerateType(String typeNameHint)
       at NJsonSchema.CodeGeneration.TypeResolverBase`1.GenerateTypes(ExtensionCode extensionCode)
       at NJsonSchema.CodeGeneration.CSharp.CSharpTypeResolver.GenerateClasses()
       at NJsonSchema.CodeGeneration.CSharp.CSharpGenerator.GenerateFile(String rootTypeNameHint)
       at ConsoleApplication2.Program.Main() in C:\Code\Tools\DAFCodeJSONGenerator\DAFCodeJSONGenerator\Program.cs:line 45
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
```
