### ISSUE TITLE
InvalidCastException on validation of JToken containing BigInteger

### ISSUE THREAD

**Issue by padluka** [RSuter/NJsonSchema#568]
Validation of JToken containing System.Numeric.BigInteger leads to InvalidCastException with message:
"Object must implement IConvertible.".
Exception is thrown on line 289 of JsonSchemaValidator(var value = token.Value<decimal>();) in method "ValidateNumber".

That's a bug because instead of receiveng error you need to handle this exception in your code.

**Comment by TomasPajurek** [comment]
I have run into similar issue with the following code and data:

- .NET Framework 4.7
- NJsonSchema 9.10.10
- Newtonsoft.Json 10.0.3

Code:
```
var schema = await JsonSchema4.FromFileAsync(...);
var jToken = JToken.Parse(...);
schema.Validate(jToken);
```
Schema:
```
{
  "type": "object",
  "properties": {
    "property1": {
      "type": "number"
    }
  },
  "required": ["property1"],
  "additionalProperties": false,
  "additionalItems": false
}
```
Data:
```
{
  "property1": 34545734242323232423434
}
```
Stack trace:
```
System.AggregateException: One or more errors occurred. ---> System.InvalidCastException: Object must implement IConvertible.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Linq.Extensions.Convert[T,U](T token)
   at Newtonsoft.Json.Linq.Extensions.Value[T,U](IEnumerable`1 value)
   at NJsonSchema.Validation.JsonSchemaValidator.ValidateNumber(JToken token, JsonSchema4 schema, JsonObjectType type, String propertyName, String propertyPath, List`1 errors)
   at NJsonSchema.Validation.JsonSchemaValidator.ValidateType(JToken token, JsonSchema4 schema, String propertyName, String propertyPath, List`1 errors)
   at NJsonSchema.Validation.JsonSchemaValidator.Validate(JToken token, JsonSchema4 schema, String propertyName, String propertyPath)
   at NJsonSchema.Validation.JsonSchemaValidator.ValidateProperties(JToken token, JsonSchema4 schema, String propertyName, String propertyPath, List`1 errors)
   at NJsonSchema.Validation.JsonSchemaValidator.Validate(JToken token, JsonSchema4 schema, String propertyName, String propertyPath)
   at NJsonSchema.Validation.JsonSchemaValidator.Validate(JToken token, JsonSchema4 schema)
   at NJsonSchema.JsonSchema4.Validate(JToken token)
```

**Comment by RSuter** [comment]
The problem here is that this is internally handled as BigInteger which is not available in .NET Standard 1.0 - any idea how we could fix this? (I've already added a unit test)

**Comment by TomasPajurek** [comment]
Are you sure? I got the error on classic .NET framework 4.7.

**Comment by RSuter** [comment]
These big integers are currently broken in all frameworks, but I couldnt find a way to implement this because the library targets .net standard 1.0

**Comment by padluka** [comment]
You can handle it like Newtonsoft.Json handled it.
#if HAVE_BIG_INTEGER
handling here
#endif

**Comment by padluka** [comment]
Or is .net standard 1.0 is your only target?

**Comment by RSuter** [comment]
It targets: netstandard1.0;net40;net45, so yes, we could do this with conditionals - but it would be great if we could also fix this in the .NET Standard target.

**Comment by padluka** [comment]
In .Net Standard this issue shouldn't exist because there are no BigInteger in it as you said.
Ugly, but surefire solution is add exception handling.

**Comment by RSuter** [comment]
The problem is, that the .NET Standard library can be used in a framework where BigInt is available and will fail there...

**Comment by padluka** [comment]
I can't think of a good solution. You can check that the value of JToken is IConvertible and in such case generate some "unsupported type" error.

**Comment by codecadwallader** [comment]
FWIW via Newtonsoft I'm using this basic workaround:
`decimal.Parse(jToken.ToString())`
