### ISSUE TITLE
Getting an Error when referencing YAML Documents

### ISSUE THREAD

**Issue by Em1ss1oN** [RSuter/NJsonSchema#736]
Our team is using NSwag to generate C# controllers from a tree of swagger contracts. Recently we transferred our contracts description from JSON to YAML, and encountered a following error on contracts that are referencing YAML document from YAML document:

> System.InvalidOperationException : Could not resolve the JSON path './collection.yaml' with the full JSON path 'C:\Work\Github\NJsonSchema\src\NJsonSchema.Yaml.Tests\bin\Debug\netcoreapp2.0\References\YamlReferencesTest\./collection.yaml'.
---- Newtonsoft.Json.JsonReaderException : Input string '---' is not a valid number. Path '', line 1, position 3.
   at NJsonSchema.JsonReferenceResolver.<ResolveFileReferenceWithAlreadyResolvedCheckAsync>d__10.MoveNext() in C:\Work\Github\NJsonSchema\src\NJsonSchema\JsonReferenceResolver.cs:line 153
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at NJsonSchema.JsonReferenceResolver.<ResolveReferenceAsync>d__9.MoveNext() in C:\Work\Github\NJsonSchema\src\NJsonSchema\JsonReferenceResolver.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NJsonSchema.JsonReferenceResolver.<ResolveReferenceWithoutAppendAsync>d__5.MoveNext() in C:\Work\Github\NJsonSchema\src\NJsonSchema\JsonReferenceResolver.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at NJsonSchema.JsonSchemaReferenceUtilities.JsonReferenceUpdater.<VisitJsonReferenceAsync>d__5.MoveNext() in C:\Work\Github\NJsonSchema\src\NJsonSchema\JsonSchemaReferenceUtilities.cs:line 113
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at NJsonSchema.Visitors.JsonReferenceVisitorBase.<VisitAsync>d__6.MoveNext() in C:\Work\Github\NJsonSchema\src\NJsonSchema\Visitors\JsonReferenceVisitorBase.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NJsonSchema.Visitors.JsonReferenceVisitorBase.<VisitAsync>d__6.MoveNext() in C:\Work\Github\NJsonSchema\src\NJsonSchema\Visitors\JsonReferenceVisitorBase.cs:line 129
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NJsonSchema.Visitors.JsonReferenceVisitorBase.<VisitAsync>d__4.MoveNext() in C:\Work\Github\NJsonSchema\src\NJsonSchema\Visitors\JsonReferenceVisitorBase.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NJsonSchema.JsonSchemaReferenceUtilities.JsonReferenceUpdater.<VisitAsync>d__4.MoveNext() in C:\Work\Github\NJsonSchema\src\NJsonSchema\JsonSchemaReferenceUtilities.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NJsonSchema.JsonSchemaReferenceUtilities.<UpdateSchemaReferencesAsync>d__1.MoveNext() in C:\Work\Github\NJsonSchema\src\NJsonSchema\JsonSchemaReferenceUtilities.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NJsonSchema.Infrastructure.JsonSchemaSerialization.<FromJsonAsync>d__9`1.MoveNext() in C:\Work\Github\NJsonSchema\src\NJsonSchema\Infrastructure\JsonSchemaSerialization.cs:line 94
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NJsonSchema.JsonSchema4.<FromJsonAsync>d__31.MoveNext() in C:\Work\Github\NJsonSchema\src\NJsonSchema\JsonSchema4.cs:line 195
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at NJsonSchema.JsonSchema4.<FromJsonAsync>d__30.MoveNext() in C:\Work\Github\NJsonSchema\src\NJsonSchema\JsonSchema4.cs:line 185
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at NJsonSchema.Yaml.JsonSchemaYaml.<FromYamlAsync>d__0.MoveNext() in C:\Work\Github\NJsonSchema\src\NJsonSchema.Yaml\JsonSchemaYaml.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at NJsonSchema.Yaml.JsonSchemaYaml.<FromFileAsync>d__2.MoveNext() in C:\Work\Github\NJsonSchema\src\NJsonSchema.Yaml\JsonSchemaYaml.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NJsonSchema.Yaml.Tests.References.LocalReferencesTests.<When_yaml_schema_has_references_it_works>d__0.MoveNext() in C:\Work\Github\NJsonSchema\src\NJsonSchema.Yaml.Tests\References\YamlReferencesTests.cs:line 22
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
   at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NJsonSchema.Infrastructure.JsonSchemaSerialization.<FromJsonAsync>d__9`1.MoveNext() in C:\Work\Github\NJsonSchema\src\NJsonSchema\Infrastructure\JsonSchemaSerialization.cs:line 83
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NJsonSchema.JsonSchema4.<FromJsonAsync>d__31.MoveNext() in C:\Work\Github\NJsonSchema\src\NJsonSchema\JsonSchema4.cs:line 195
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at NJsonSchema.JsonSchema4.<FromFileAsync>d__26.MoveNext() in C:\Work\Github\NJsonSchema\src\NJsonSchema\JsonSchema4.cs:line 142
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at NJsonSchema.JsonReferenceResolver.<ResolveFileReferenceAsync>d__7.MoveNext() in C:\Work\Github\NJsonSchema\src\NJsonSchema\JsonReferenceResolver.cs:line 83
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at NJsonSchema.JsonReferenceResolver.<ResolveFileReferenceWithAlreadyResolvedCheckAsync>d__10.MoveNext() in C:\Work\Github\NJsonSchema\src\NJsonSchema\JsonReferenceResolver.cs:line 140

If references are JSON Documents, everything works fine regardless of whether the root document is JSON or YAML
Looks like YAML to JSON conversion is performed only for root document.

**Comment by RSuter** [comment]
I hope my changes are ok for you? The unit tests are passing...

**Comment by Em1ss1oN** [comment]
Everything is ok, thanks. I'll look into injecting these changes into NSwag and create issue for it.

**Comment by RSuter** [comment]
Im the maintainer of nswag too, release should be soon
