### ISSUE TITLE
Validate() throws exception on non-JSON string

### ISSUE THREAD

**Issue by RodneyRichardson** [RSuter/NJsonSchema#776]
When validating an invalid JSON document (truncated), I would expect Validate() to return an appropriate `ValidationError`. Instead it throws a `JsonReaderException` (thrown by `JsonTextReader`):

```
Newtonsoft.Json.JsonReaderException: Unterminated string. Expected delimiter: ". Path 'blah', line 3, position 64.
   at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings)
   at NJsonSchema.JsonSchema4.Validate(String jsonData)
```

Suggest catching this exception, and adding a new `ValidationErrorKind`.

**Comment by RSuter** [comment]
Yes, why not... it may be a breaking change for some - but fine for me. Can you create a PR?

**Comment by RodneyRichardson** [comment]
I am happy to do that

**Comment by RodneyRichardson** [comment]
Looking on more details, this doesn't really fit in with what the ValidationError encapsulated (i.e. an error with a specific property). JsonReaderException doesn't map cleanly to this, so I think it's nicer to leae it as it is. I'm happy for this to be resolved as "Won't fix", or perhaps just update documentation?

**Comment by RSuter** [comment]
Updated wiki: https://github.com/RSuter/NJsonSchema/wiki/JsonSchemaValidator
