### ISSUE TITLE
Schema object creating failed with: Could not resolve the path '#/definitions/xxx' with a very simple schema

### ISSUE THREAD

**Issue by lbcsy** [RSuter/NJsonSchema#807]
Why I got "Message: System.InvalidOperationException : Could not resolve the path '#/definitions/ValueSet'." in following test? 
[Fact]
public async Task When_ref_is_nested_then_it_should_be_resolved()
  {
            /// Arrange
    var jsonschemastr = @"{
    ""$schema"": ""http://json-schema.org/draft-04/schema#"",
    ""$ref"": ""#/definitions/ValueSet"",
    ""definitions"": {
        ""ResourceList"": {
            ""oneOf"": [
                {
                    ""properties"": {}
                },
                {
                    ""$ref"": ""#/definitions/CodeSystem""
                },
                {
                    ""$ref"": ""#/definitions/ValueSet""
                }
            ]
        },
        ""CodeSystem"": {
            
        },
        ""ValueSet"": {
        },
        
    }
}";

            /// Act
            var schema = await JsonSchema4.FromJsonAsync(jsonschemastr);

            /// Assert
            var jsonOutput = schema.ToJson();
            Assert.NotNull(jsonOutput);
        }
    }

**Comment by RicoSuter** [comment]
Is this still an issue in the latest version?

**Comment by alski** [comment]
I believe so. Extract of our generated swagger.json

 "JsonPrimitive": {
      "type": "object",
      "properties": {
        "asBoolean": {
          "type": "boolean"
        },
        "boolean": {
          "type": "boolean"
        },

Yet we get 

System.InvalidOperationException: Could not resolve the path '#/definitions/Boolean'.

Runtime: NetCore21
   at NJsonSchema.JsonReferenceResolver.ResolveDocumentReference(Object rootObject, String jsonPath)
   at NJsonSchema.JsonReferenceResolver.ResolveReferenceAsync(Object rootObject, String jsonPath, Boolean append)
   at NJsonSchema.JsonReferenceResolver.ResolveReferenceAsync(Object rootObject, String jsonPath)
   at NJsonSchema.JsonSchemaReferenceUtilities.JsonReferenceUpdater.VisitJsonReferenceAsync(IJsonReference reference, String path, String typeNameHint)
   at NJsonSchema.Visitors.JsonReferenceVisitorBase.VisitAsync(Object obj, String path, String typeNameHint, ISet`1 checkedObjects, Action`1 replacer)
   at NJsonSchema.Visitors.JsonReferenceVisitorBase.VisitPropertiesAsync(Object obj, String path, ISet`1 checkedObjects)
   at NJsonSchema.Visitors.JsonReferenceVisitorBase.VisitAsync(Object obj, String path, String typeNameHint, ISet`1 checkedObjects, Action`1 replacer)
   at NJsonSchema.Visitors.JsonReferenceVisitorBase.VisitAsync(Object obj, String path, String typeNameHint, ISet`1 checkedObjects, Action`1 replacer)
   at NJsonSchema.Visitors.JsonReferenceVisitorBase.VisitPropertiesAsync(Object obj, String path, ISet`1 checkedObjects)
   at NJsonSchema.Visitors.JsonReferenceVisitorBase.VisitAsync(Object obj, String path, String typeNameHint, ISet`1 checkedObjects, Action`1 replacer)
   at NJsonSchema.Visitors.JsonReferenceVisitorBase.VisitPropertiesAsync(Object obj, String path, ISet`1 checkedObjects)
   at NJsonSchema.Visitors.JsonReferenceVisitorBase.VisitAsync(Object obj, String path, String typeNameHint, ISet`1 checkedObjects, Action`1 replacer)
   at NJsonSchema.Visitors.JsonReferenceVisitorBase.VisitPropertiesAsync(Object obj, String path, ISet`1 checkedObjects)
   at NJsonSchema.Visitors.JsonReferenceVisitorBase.VisitAsync(Object obj, String path, String typeNameHint, ISet`1 checkedObjects, Action`1 replacer)
   at NJsonSchema.Visitors.JsonReferenceVisitorBase.VisitAsync(Object obj, String path, String typeNameHint, ISet`1 checkedObjects, Action`1 replacer)
   at NJsonSchema.Visitors.JsonReferenceVisitorBase.VisitAsync(Object obj, String path, String typeNameHint, ISet`1 checkedObjects, Action`1 replacer)
   at NJsonSchema.Visitors.JsonReferenceVisitorBase.VisitPropertiesAsync(Object obj, String path, ISet`1 checkedObjects)
   at NJsonSchema.Visitors.JsonReferenceVisitorBase.VisitAsync(Object obj, String path, String typeNameHint, ISet`1 checkedObjects, Action`1 replacer)
   at NJsonSchema.Visitors.JsonReferenceVisitorBase.VisitPropertiesAsync(Object obj, String path, ISet`1 checkedObjects)
   at NJsonSchema.Visitors.JsonReferenceVisitorBase.VisitAsync(Object obj, String path, String typeNameHint, ISet`1 checkedObjects, Action`1 replacer)
   at NJsonSchema.Visitors.JsonReferenceVisitorBase.VisitPropertiesAsync(Object obj, String path, ISet`1 checkedObjects)
   at NJsonSchema.Visitors.JsonReferenceVisitorBase.VisitAsync(Object obj, String path, String typeNameHint, ISet`1 checkedObjects, Action`1 replacer)
   at NJsonSchema.Visitors.JsonReferenceVisitorBase.VisitAsync(Object obj)
   at NJsonSchema.JsonSchemaReferenceUtilities.JsonReferenceUpdater.VisitAsync(Object obj)
   at NJsonSchema.JsonSchemaReferenceUtilities.UpdateSchemaReferencesAsync(Object rootObject, JsonReferenceResolver referenceResolver, IContractResolver contractResolver)
   at NJsonSchema.Infrastructure.JsonSchemaSerialization.FromJsonAsync[T](String json, SchemaType schemaType, String documentPath, Func`2 referenceResolverFactory, IContractResolver contractResolver)
   at NSwag.SwaggerDocument.FromJsonAsync(String data, String documentPath, SchemaType expectedSchemaType, Func`2 referenceResolverFactory) in C:\projects\nswag\src\NSwag.Core\SwaggerDocument.cs:line 187
   at NSwag.Commands.OutputCommandBase.ReadSwaggerDocumentAsync(String input) in C:\projects\nswag\src\NSwag.Commands\Commands\OutputCommandBase.cs:line 54
   at NSwag.Commands.SwaggerGeneration.FromSwaggerCommand.RunAsync() in C:\projects\nswag\src\NSwag.Commands\Commands\SwaggerGeneration\FromSwaggerCommand.cs:line 62
   at NSwag.Commands.SwaggerGeneration.FromSwaggerCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\SwaggerGeneration\FromSwaggerCommand.cs:line 53
   at NSwag.Commands.NSwagDocumentBase.GenerateSwaggerDocumentAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocumentBase.cs:line 268
   at NSwag.Commands.NSwagDocument.ExecuteAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocument.cs:line 81
   at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 77
   at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 31
   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in C:\projects\nswag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 54

**Comment by abesting** [comment]
Any chance that it will be fixed in the future? I'm currently working with version 10.1.12 and I have similar problems resolving paths...

**Comment by RicoSuter** [comment]
Strange, can you create a PR with a unit test repro?
