### ISSUE TITLE
Custom reference resolver fails when trying to resolve a file reference

### ISSUE THREAD

**Issue by JPAhnen** [RSuter/NJsonSchema#850]
So I want to reference another file in my schema, but this file is an embedded resource and (at runtime) does not exist on disk.

```
{
   "$schema": "http://json-schema.org/draft-07/schema#",
   "$id": "https://blubb.com/schemas/outer.schema.json",
   "type": "object",
   "additionalProperties": false,
   "required": [
      "type",
      "captions"
   ],
   "properties": {
      "captions": {
         "$ref": "definitions.schema.json#/definitions/captions"
      }
   }
}
```

And this is `definitions.schema.json`:
```
{
   "definitions": {
      "captions": {
         "type": "object"
      }
   }
}
```

This works fine in Visual Studio, since both files exist and are in the same directory. But I need the validation during runtime, and so these files are all embedded resources.
To redirect NJSonSchema to point to the correct content, I did this:

```
string definitionsSchemaContent = "..."; // read from embedded file
string schema = "..."; // outer schema referencing captions

var jsonSchema = await JsonSchema4.FromJsonAsync(
                      schema,
                      string.Empty,
                      schema4 =>
                         {
                            JsonSchemaResolver schemaResolver = new JsonSchemaResolver(
                               schema4,
                               new JsonSchemaGeneratorSettings());

                            var resolver = new JsonReferenceResolver(schemaResolver);
                            // someone referencing "definitions.schema.json? Use this content instead
                            resolver.AddDocumentReference("definitions.schema.json", definitionsSchemaContent);

                            return resolver;
                         });
```

But this fails with
```
Message: System.AggregateException : One or more errors occurred. (Exception has been thrown by the target of an invocation.)
---- System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
-------- System.ArgumentNullException : Value cannot be null.
Parameter name: path1

at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at NJsonSchema.Infrastructure.DynamicApis.PathCombine(String path1, String path2)
at NJsonSchema.JsonReferenceResolver.ResolveReferenceAsync(Object rootObject, String jsonPath, Boolean append)
at NJsonSchema.JsonReferenceResolver.ResolveReferenceAsync(Object rootObject, String jsonPath)
at NJsonSchema.JsonSchemaReferenceUtilities.JsonReferenceUpdater.VisitJsonReferenceAsync(IJsonReference reference, String path, String typeNameHint)
at NJsonSchema.Visitors.JsonReferenceVisitorBase.VisitAsync(Object obj, String path, String typeNameHint, ISet`1 checkedObjects, Action`1 replacer)
at NJsonSchema.Visitors.JsonReferenceVisitorBase.VisitAsync(Object obj, String path, String typeNameHint, ISet`1 checkedObjects, Action`1 replacer)
at NJsonSchema.Visitors.JsonReferenceVisitorBase.VisitAsync(Object obj)
at NJsonSchema.JsonSchemaReferenceUtilities.JsonReferenceUpdater.VisitAsync(Object obj)
at NJsonSchema.JsonSchemaReferenceUtilities.UpdateSchemaReferencesAsync(Object rootObject, JsonReferenceResolver referenceResolver, IContractResolver contractResolver)
at NJsonSchema.Infrastructure.JsonSchemaSerialization.FromJsonAsync[T](String json, SchemaType schemaType, String documentPath, Func`2 referenceResolverFactory, IContractResolver contractResolver)
at NJsonSchema.JsonSchema4.FromJsonAsync(String data, String documentPath, Func`2 referenceResolverFactory)
```

Obviously, because I have no paths anywhere, `Path.Combine` will fail because the first argument is empty. I believe this is the line which fails: https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema/JsonReferenceResolver.cs#L135

If I prefix the `$ref` value with `http://` and use `resolver.AddDocumentReference("http://definitions.schema.json", definitionsSchemaContent);`, everything works, but of course now Visual Studio complains that it can't resolve the reference.

Is this a bug? Or can I somehow use a fake path (e.g. `C:\temp`) to trick `Path.Combine` into using something valid?

**Comment by aw129** [comment]
Try using a document path of `"."` instead of `String.Empty` for the `JsonSchema4.FromJsonAsync` call. This worked for me.

**Comment by JPAhnen** [comment]
Thanks a lot, this did solve my problem!
